TED_BATCH_HEADER_SCHEMA = [
    {"name": "bank_code", "start": 1, "end": 3, "type": "num", "required": True},
    {"name": "service_batch", "start": 4, "end": 7, "type": "num", "required": True},
    {"name": "record_type", "start": 8, "end": 8, "type": "num", "required": True},
    {"name": "operation_type", "start": 9, "end": 9, "type": "alpha", "required": True},
    {"name": "service_type", "start": 10, "end": 11, "type": "num", "required": True},
    {"name": "entry_form", "start": 12, "end": 13, "type": "num", "required": True},
    {"name": "layout_version", "start": 14, "end": 16, "type": "num", "required": True},
    {"name": "tax_id_type", "start": 18, "end": 18, "type": "num", "required": True},
    {"name": "tax_id_number", "start": 19, "end": 32, "type": "num", "required": True},
    {"name": "contract_code", "start": 33, "end": 52, "type": "alpha", "required": False},
    {"name": "branch_code", "start": 53, "end": 57, "type": "num", "required": True},
    {"name": "branch_digit", "start": 58, "end": 58, "type": "alpha", "required": False},
    {"name": "account_number", "start": 59, "end": 70, "type": "num", "required": True},
    {"name": "account_digit", "start": 71, "end": 71, "type": "alpha", "required": False},
    {"name": "company_name", "start": 73, "end": 102, "type": "alpha", "required": True},
    {"name": "message", "start": 103, "end": 142, "type": "alpha", "required": False},
    {"name": "address", "start": 143, "end": 172, "type": "alpha", "required": True},
    {"name": "address_number", "start": 173, "end": 177, "type": "num", "required": False},
    {"name": "address_complement", "start": 178, "end": 192, "type": "alpha", "required": False},
    {"name": "city", "start": 193, "end": 212, "type": "alpha", "required": True},
    {"name": "zip_code", "start": 213, "end": 217, "type": "num", "required": True},
    {"name": "zip_suffix", "start": 218, "end": 220, "type": "alpha", "required": False},
    {"name": "state", "start": 221, "end": 222, "type": "alpha", "required": True},
    {"name": "payment_method", "start": 223, "end": 224, "type": "num", "required": True},
]
