BOLETOS_SEGMENT_J52_SCHEMA = [
    {"name": "bank_code", "start": 1, "end": 3, "type": "num"},
    {"name": "service_batch", "start": 4, "end": 7, "type": "num"},
    {"name": "record_type", "start": 8, "end": 8, "type": "num"},
    {"name": "record_seq", "start": 9, "end": 13, "type": "num"},
    {"name": "segment_code", "start": 14, "end": 14, "type": "alpha"},
    {"name": "cnab_1", "start": 15, "end": 15, "type": "alpha"},
    {"name": "movement_code", "start": 16, "end": 17, "type": "num"},
    {"name": "optional_record_code", "start": 18, "end": 19, "type": "num"},
    {"name": "payer_doc_type", "start": 20, "end": 20, "type": "num"},
    {"name": "payer_doc_number", "start": 21, "end": 35, "type": "num"},
    {"name": "payer_name", "start": 36, "end": 75, "type": "alpha"},
    {"name": "beneficiary_doc_type", "start": 76, "end": 76, "type": "num"},
    {"name": "beneficiary_doc_number", "start": 77, "end": 91, "type": "num"},
    {"name": "beneficiary_name", "start": 92, "end": 131, "type": "alpha"},
    {"name": "final_beneficiary_doc_type", "start": 132, "end": 132, "type": "num"},
    {"name": "final_beneficiary_doc_number", "start": 133, "end": 147, "type": "num"},
    {"name": "final_beneficiary_name", "start": 148, "end": 187, "type": "alpha"},
    {"name": "cnab_2", "start": 188, "end": 240, "type": "alpha"},
]
