BOLETOS_SEGMENT_J_SCHEMA = [
    {"name": "bank_code", "start": 1, "end": 3, "type": "num"},
    {"name": "service_batch", "start": 4, "end": 7, "type": "num"},
    {"name": "record_type", "start": 8, "end": 8, "type": "num"},
    {"name": "record_seq", "start": 9, "end": 13, "type": "num"},
    {"name": "segment_code", "start": 14, "end": 14, "type": "alpha"},
    {"name": "movement_type", "start": 15, "end": 15, "type": "num"},
    {"name": "instruction_code", "start": 16, "end": 17, "type": "num"},
    {"name": "barcode", "start": 18, "end": 61, "type": "num"},
    {"name": "assignor_name", "start": 62, "end": 91, "type": "alpha"},
    {"name": "due_date", "start": 92, "end": 99, "type": "num"},
    {"name": "boleto_amount", "start": 100, "end": 114, "type": "num"},
    {"name": "discount_value", "start": 115, "end": 129, "type": "num"},
    {"name": "fine_value", "start": 130, "end": 144, "type": "num"},
    {"name": "pay_day", "start": 145, "end": 152, "type": "num"},
    {"name": "payment_amount", "start": 153, "end": 167, "type": "num"},
    {"name": "currency_quantity", "start": 168, "end": 182, "type": "num"},
    {"name": "company_doc_number", "start": 183, "end": 202, "type": "alpha"},
    {"name": "bank_doc_number", "start": 203, "end": 222, "type": "alpha"},
    {"name": "currency_code", "start": 223, "end": 224, "type": "num"},
    {"name": "cnab", "start": 225, "end": 230, "type": "alpha"},
    {"name": "occurrences", "start": 231, "end": 240, "type": "alpha"},
]
