file_header_schema = [
    {"name": "bank_code", "start": 1, "end": 3, "length": 3, "type": "num", "required": True},
    {"name": "service_batch", "start": 4, "end": 7, "length": 4, "type": "num", "required": True},
    {"name": "record_type", "start": 8, "end": 8, "length": 1, "type": "num", "required": True},
    {"name": "cnab", "start": 9, "end": 17, "length": 9, "type": "alpha", "required": False},
    {"name": "tax_id_type", "start": 18, "end": 18, "length": 1, "type": "num", "required": True},
    {"name": "tax_id_number", "start": 19, "end": 32, "length": 14, "type": "num", "required": True},
    {"name": "contract_code", "start": 33, "end": 52, "length": 20, "type": "alpha", "required": False},
    {"name": "branch_code", "start": 53, "end": 57, "length": 5, "type": "num", "required": True},
    {"name": "branch_check_digit", "start": 58, "end": 58, "length": 1, "type": "alpha", "required": False},
    {"name": "account_number", "start": 59, "end": 70, "length": 12, "type": "num", "required": True},
    {"name": "account_check_digit", "start": 71, "end": 71, "length": 1, "type": "alpha", "required": True},
    {"name": "company_name", "start": 73, "end": 102, "length": 30, "type": "alpha", "required": True},
    {"name": "bank_name", "start": 103, "end": 132, "length": 30, "type": "alpha", "required": True},
    {"name": "file_code", "start": 143, "end": 143, "length": 1, "type": "num", "required": True},
    {"name": "generation_date", "start": 144, "end": 151, "length": 8, "type": "num", "required": True},
    {"name": "generation_time", "start": 152, "end": 157, "length": 6, "type": "num", "required": True},
    {"name": "file_sequence", "start": 158, "end": 163, "length": 6, "type": "num", "required": True},
    {"name": "layout_version", "start": 164, "end": 166, "length": 3, "type": "num", "required": True},
]
