SEGMENT_A_SCHEMA = [
    {"name": "bank_code", "start": 1, "end": 3, "type": "num", "required": True},
    {"name": "service_batch", "start": 4, "end": 7, "type": "num", "required": True},
    {"name": "record_type", "start": 8, "end": 8, "type": "num", "required": True},
    {"name": "record_number", "start": 9, "end": 13, "type": "num", "required": True},
    {"name": "segment_code", "start": 14, "end": 14, "type": "alpha", "required": True},
    {"name": "transaction_type", "start": 15, "end": 15, "type": "num", "required": True},
    {"name": "instruction_code", "start": 16, "end": 17, "type": "num", "required": True},
    {"name": "clearing_code", "start": 18, "end": 20, "type": "num", "required": True},
    {"name": "payee_bank_code", "start": 21, "end": 23, "type": "num", "required": True},
    {"name": "branch_code", "start": 25, "end": 28, "type": "num", "required": True},
    {"name": "branch_digit", "start": 29, "end": 29, "type": "alpha", "required": False},
    {"name": "account_number", "start": 30, "end": 41, "type": "num", "required": True},
    {"name": "account_digit", "start": 42, "end": 42, "type": "alpha", "required": False},
    {"name": "payer_name", "start": 44, "end": 73, "type": "alpha", "required": True},
    {"name": "reference_number", "start": 74, "end": 93, "type": "alpha", "required": False},
    {"name": "payment_date", "start": 94, "end": 101, "type": "num", "required": True},
    {"name": "currency_type", "start": 102, "end": 104, "type": "alpha", "required": True},
    {"name": "currency_amount", "start": 105, "end": 119, "type": "num", "required": True},
    {"name": "payment_amount", "start": 120, "end": 134, "type": "num", "required": True},
    {"name": "bank_ref", "start": 135, "end": 154, "type": "alpha", "required": False},
    {"name": "effective_date", "start": 155, "end": 162, "type": "num", "required": False},
    {"name": "effective_value", "start": 163, "end": 177, "type": "num", "required": False},
    {"name": "ted_purpose", "start": 220, "end": 224, "type": "alpha", "required": False},
]

