
SEGMENT_B_SCHEMA = [
    {"name": "bank_code", "start": 1, "end": 3, "type": "num"},
    {"name": "service_batch", "start": 4, "end": 7, "type": "num"},
    {"name": "record_type", "start": 8, "end": 8, "type": "num"},
    {"name": "record_number", "start": 9, "end": 13, "type": "num"},
    {"name": "segment_code", "start": 14, "end": 14, "type": "alpha"},
    {"name": "beneficiary_tax_id_type", "start": 18, "end": 18, "type": "num"},
    {"name": "beneficiary_tax_id", "start": 19, "end": 32, "type": "num"},
    {"name": "address", "start": 33, "end": 62, "type": "alpha"},
    {"name": "address_number", "start": 63, "end": 67, "type": "num"},
    {"name": "address_complement", "start": 68, "end": 82, "type": "alpha"},
    {"name": "neighborhood", "start": 83, "end": 97, "type": "alpha"},
    {"name": "city", "start": 98, "end": 117, "type": "alpha"},
    {"name": "zip_code", "start": 118, "end": 122, "type": "num"},
    {"name": "zip_suffix", "start": 123, "end": 125, "type": "alpha"},
    {"name": "state", "start": 126, "end": 127, "type": "alpha"},
    {"name": "expiration_date", "start": 128, "end": 135, "type": "num"},
    {"name": "document_value", "start": 136, "end": 150, "type": "num"},
    {"name": "rebate", "start": 151, "end": 165, "type": "num"},
    {"name": "discount", "start": 166, "end": 180, "type": "num"},
    {"name": "mortgage", "start": 181, "end": 195, "type": "num"},
    {"name": "fine", "start": 196, "end": 210, "type": "num"},
    {"name": "beneficiary_code", "start": 211, "end": 225, "type": "alpha"},
    {"name": "notice", "start": 226, "end": 226, "type": "num"},
    {"name": "centralizing_ug_code", "start": 227, "end": 232, "type": "num"},
    {"name": "ispb_code", "start": 233, "end": 240, "type": "num"},
]

